"""
Report generation utilities for the
Windows Service & Process Monitoring Agent.
"""

from datetime import datetime

from core.risk_engine import RiskEngine
from utils.logger import Logger


class ReportGenerator:
    """
    Generates security assessment reports
    from collected findings.
    """

    def __init__(self) -> None:
        """
        Initialize the report generator.
        """

        self.logger = Logger()

        self.risk_engine = RiskEngine()

    def generate_console_report(
        self,
        processes: list[dict[str, object]],
        services: list[dict[str, object]],
        findings: list[dict[str, str]],
    ) -> None:
        """
        Generate a formatted security report.

        Args:
            processes:
                Collected process information.

            services:
                Collected Windows services.

            findings:
                Security findings generated by
                the Detection Engine.
        """

        overall_score = self.risk_engine.calculate_overall(
            findings
        )

        overall_severity = (
            self.risk_engine.score_to_severity(
                overall_score
            )
        )

        statistics = self.risk_engine.statistics(
            findings
        )

        print()
        print("=" * 100)
        print("WINDOWS SERVICE & PROCESS MONITORING AGENT")
        print("Security Assessment Report")
        print("=" * 100)

        print("\nScan Information")
        print("-" * 100)

        print(
            f"Scan Time          : "
            f"{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
        )

        print(
            f"Processes Scanned  : {len(processes)}"
        )

        print(
            f"Services Scanned   : {len(services)}"
        )

        print()

        print("=" * 100)
        print("OVERALL RISK")
        print("=" * 100)

        print(f"Risk Score         : {overall_score}")
        print(f"Risk Level         : {overall_severity}")

        print()

        print("=" * 100)
        print("FINDING SUMMARY")
        print("=" * 100)

        print(
            f"Critical Findings  : "
            f"{statistics['CRITICAL']}"
        )

        print(
            f"High Findings      : "
            f"{statistics['HIGH']}"
        )

        print(
            f"Medium Findings    : "
            f"{statistics['MEDIUM']}"
        )

        print(
            f"Low Findings       : "
            f"{statistics['LOW']}"
        )

        print(
            f"Informational      : "
            f"{statistics['INFO']}"
        )

        print()

        print("=" * 100)
        print("SECURITY FINDINGS")
        print("=" * 100)

        if not findings:

            print("\nNo security findings detected.")

        else:

            for index, finding in enumerate(
                findings,
                start=1,
            ):

                print(f"\nFinding #{index}")

                print(
                    f"Severity       : "
                    f"{finding['severity']}"
                )

                print(
                    f"Category       : "
                    f"{finding['category']}"
                )

                print(
                    f"Title          : "
                    f"{finding['title']}"
                )

                print(
                    f"Description    : "
                    f"{finding['description']}"
                )

                print(
                    f"Recommendation : "
                    f"{finding['recommendation']}"
                )

                print("-" * 100)

        print()
        print("=" * 100)
        print("END OF REPORT")
        print("=" * 100)

        self.logger.info(
            "Security assessment report generated."
        )