"""
Finding statistics section for the
Windows Service & Process Monitoring Agent PDF report.
"""


def build_finding_statistics(
    findings: list[dict[str, str]],
) -> dict[str, int]:
    """
    Calculate the number of findings for each severity level.

    Args:
        findings:
            Security findings generated by the monitoring agent.

    Returns:
        Dictionary containing finding counts by severity.
    """

    statistics = {
        "CRITICAL": 0,
        "HIGH": 0,
        "MEDIUM": 0,
        "LOW": 0,
        "INFO": 0,
    }

    for finding in findings:

        severity = str(
            finding.get("severity", "INFO")
        ).upper()

        if severity in statistics:
            statistics[severity] += 1

    return statistics