"""
Security findings section for the
Windows Service & Process Monitoring Agent PDF report.
"""


def build_security_findings(
    findings: list[dict[str, str]],
) -> list[dict[str, str]]:
    """
    Prepare security findings for the assessment report.

    Args:
        findings:
            Combined findings generated by the detection,
            startup audit, and digital signature engines.

    Returns:
        List of formatted security findings.
    """

    security_findings: list[dict[str, str]] = []

    for finding in findings:

        security_findings.append(
            {
                "severity": str(
                    finding.get("severity") or "INFO"
                ).upper(),
                "category": str(
                    finding.get("category") or "Unknown"
                ),
                "title": str(
                    finding.get("title") or "Unknown Finding"
                ),
                "description": str(
                    finding.get("description")
                    or "No description available."
                ),
                "recommendation": str(
                    finding.get("recommendation")
                    or "Review the finding and verify whether the activity is expected."
                ),
            }
        )

    return security_findings