"""
Startup service audit section for the
Windows Service & Process Monitoring Agent PDF report.
"""


def build_startup_audit(
    automatic_services: list[dict[str, object]],
    findings: list[dict[str, str]],
) -> dict[str, object]:
    """
    Prepare startup service audit information
    for the security assessment report.

    Args:
        automatic_services:
            Windows services configured to start automatically.

        findings:
            Findings generated by the StartupAudit engine.

    Returns:
        Dictionary containing startup service information
        and audit findings.
    """

    services: list[dict[str, str]] = []

    for service in automatic_services:

        services.append(
            {
                "name": str(
                    service.get("name") or "N/A"
                ),
                "state": str(
                    service.get("state") or "N/A"
                ),
                "account": str(
                    service.get("account") or "N/A"
                ),
                "start_mode": str(
                    service.get("start_mode") or "N/A"
                ),
                "path": str(
                    service.get("path") or "N/A"
                ),
            }
        )

    return {
        "automatic_services": services,
        "findings": findings.copy(),
        "automatic_service_count": len(services),
        "finding_count": len(findings),
    }